server:
  port: 8080

spring:
  application:
    name: car_rental_system
  profiles:
    active: dev
  datasource:  # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8+ 驱动
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai  # 补充时区和编码参数
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    username: ${car_rental_system.mail.username}
    password: ${car_rental_system.mail.password}
    host: ${car_rental_system.mail.host}
#    rabbitmq的配置
  rabbitmq:
    host: 192.168.220.128 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: 1234 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # mapper.xml文件路径
  type-aliases-package: com.hosiky.domain.po # 实体类所在包
  type-enums-package: com.hosiky.common.entity.Enum
  configuration:
    map-underscore-to-camel-case: true  # 关闭驼峰命名转换（根据实际需求调整）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志
  global-config:
    db-config:
      id-type: auto  # 主键自增（根据数据库类型调整）


minio:
  endpoint: ${car_rental_system.minio.endpoint}
  access-key: ${car_rental_system.minio.access-key}
  secret-key: ${car_rental_system.minio.secret-key}
  bucket-name: ${car_rental_system.minio.bucket-name}
  base-url: ${car_rental_system.minio.base-url}



# JWT配置
jwt:
  secret-key: "0123456789abcdef0123456789abcdef"
  ttl: 7200000  # 令牌有效期（7200000毫秒 = 2小时）
  token-name: token  # 请求头中的令牌键名（如Authorization: token值）

logging:
  level:
    org.springframework.beans.factory.support.FactoryBeanRegistrySupport: debug
    org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory: debug
    org.mybatis.spring.mapper.MapperScannerConfigurer: debug