server:
  port: 8080

spring:
  application:
    name: car_rental_system
  profiles:
    active: dev
  datasource:  # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8+ 驱动
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai  # 补充时区和编码参数
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    username: ${car_rental_system.mail.username}
    password: ${car_rental_system.mail.password}
    host: ${car_rental_system.mail.host}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # mapper.xml文件路径
  type-aliases-package: com.hosiky.domain.po # 实体类所在包
  type-enums-package: com.hosiky.common.entity.Enum
  configuration:
    map-underscore-to-camel-case: true  # 关闭驼峰命名转换（根据实际需求调整）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志
  global-config:
    db-config:
      id-type: auto  # 主键自增（根据数据库类型调整）

# JWT配置
jwt:
  secret-key: "0123456789abcdef0123456789abcdef"
  ttl: 7200000  # 令牌有效期（7200000毫秒 = 2小时）
  token-name: token  # 请求头中的令牌键名（如Authorization: token值）

logging:
  level:
    org.springframework.beans.factory.support.FactoryBeanRegistrySupport: debug
    org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory: debug
    org.mybatis.spring.mapper.MapperScannerConfigurer: debug