server:
  port: 8080

spring:
  application:
    name: car_rental_system
  profiles:
    active: dev
  datasource:  # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8+ 驱动
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai  # 补充时区和编码参数
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    username: ${car_rental_system.mail.username}
    password: ${car_rental_system.mail.password}
    host: ${car_rental_system.mail.host}

logging:
  level:
    org.springframework.beans.factory.support.FactoryBeanRegistrySupport: debug
    org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory: debug
    org.mybatis.spring.mapper.MapperScannerConfigurer: debug